name: streaming_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^2.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  dio: ^4.0.0
  flash: ^2.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.17.0
  flutter_secure_storage: ^4.2.1
  freezed_annotation: ^0.14.1
  hooks_riverpod: ^0.14.0+4
  json_annotation: ^4.0.1
  material_design_icons_flutter: ^5.0.5955-rc.1
  sembast: ^3.1.0+2
  path_provider: ^2.0.2
  path: ^1.8.0

dev_dependencies:
  auto_route_generator: ^2.1.0

  build_runner: null
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1+3
  json_serializable: ^4.1.0
  lint: ^1.5.3

flutter:
  uses-material-design: true
